# Generated by Django 6.1.1 on 2026-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2083)),
                ('interval', models.PositiveIntegerField(default=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('up', 'Up'), ('down', 'Down')], default='pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
