# Generated by Django 6.1.1 on 2026-09-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.IntegerField()),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, default='')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitor.monitor')),
            ],
        ),
    ]
